[package]
name = "server"
version = "0.1.0"
authors = ["Andy Pau <andy.pau@qq.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = false

[dependencies]
nickel = "0.11.0"
